version: '3'
services:
  mongodb:
    build: db/.
    container_name: "db"
    ports:
     - "27017:27017"
    environment:
     - MONGO_ROOT_PASSWORD=password123
  web:
    build: .
    ports: 
     - "3000:3000"
